import { NgModule } from '@angular/core';
import {  PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { AppRoutingPreloaderService } from './providers/AppRoutingPreloaderService';

const routes: Routes = [
  { path: '', loadChildren: () => import( './tabs/tabs.module').then( m => m.TabsPageModule)  },
  { path: 'app', loadChildren: () => import( './tabs/tabs.module').then( m => m.TabsPageModule) },
  { path: 'showmore', loadChildren: () => import( './tabs/tabs.module').then( m => m.TabsPageModule) },
  { path: 'pickup-calendar/:openfrommain', loadChildren: () => import( './pickup-calendar/pickup-calendar.module').then( m => m.PickupCalendarPageModule) },
  { path: 'login', loadChildren: () => import( './login/login.module').then( m => m.LoginPageModule) },
  { path: 'loginusername', loadChildren: () => import( './loginusername/loginusername.module').then( m => m.LoginusernamePageModule) },
  { path: 'occupancy', loadChildren: () => import( './occupancy/occupancy.module').then( m => m.OccupancyPageModule) },
  { path: 'searchhotel/:id/:text', loadChildren: () => import( './searchhotel/searchhotel.module').then( m => m.SearchHotelPageModule) },
  { path: 'searchhotelfilter', loadChildren: () => import( './search-hotel-filter/search-hotel-filter.module').then( m => m.SearchHotelFilterPageModule) },
  { path: 'searchhotelfilteragain', loadChildren: () => import( './search-hotel-filter-again/search-hotel-filter-again.module').then( m => m.SearchHotelFilterAgainPageModule) },
  { path: 'searchhotelfilterandsort', loadChildren: () => import( './search-hotel-filter-and-sort/search-hotel-filter-and-sort.module').then( m => m.SearchHotelFilterAndSortPageModule) },
  { path: 'hotellist/:filteragain', loadChildren: () => import( './hotel-list/hotel-list.module').then( m => m.HotelListPageModule) },
  { path: 'hotellistmood/:id/:title', loadChildren: () => import( './hotel-list-mood/hotel-list-mood.module').then( m => m.HotelListMoodPageModule) },
  { path: 'hoteldetail/:id', loadChildren: () => import( './hoteldetail/hoteldetail.module').then( m => m.HotelDetailPageModule) },
  { path: 'hotelroomdetail/:id', loadChildren: () => import( './hotelroomdetail/hotelroomdetail.module').then( m => m.HotelRoomDetailPageModule) },
  { path: 'hotelreviews/:id', loadChildren: () => import( './hotelreviews/hotelreviews.module').then( m => m.HotelReviewsPageModule) },
  { path: 'hoteldescription/:id', loadChildren: () => import( './description/description.module').then( m => m.DescriptionPageModule) },
  { path: 'facilities/:id', loadChildren: () => import( './facilities/facilities.module').then( m => m.FacilitiesPageModule) },
  { path: 'policy/:id', loadChildren: () => import( './policy/policy.module').then( m => m.PolicyPageModule) },
  { path: 'userprofile', loadChildren: () => import( './userprofile/userprofile.module').then( m => m.UserProfilePageModule) },
  { path: 'userreviews', loadChildren: () => import( './userreviews/userreviews.module').then( m => m.UserReviewsPageModule) },
  { path: 'userreward', loadChildren: () => import( './userreward/userreward.module').then( m => m.UserRewardPageModule) },
  { path: 'tripweather/:cityName', loadChildren: () => import( './weather/weather.module').then( m => m.WeatherPageModule) },
  { path: 'exchangegift/cityName', loadChildren: () => import( './exchangegift/exchangegift.module').then( m => m.ExchangeGiftPageModule) },
  { path: 'cuspoints', loadChildren: () => import( './cuspoints/cuspoints.module').then( m => m.CuspointsPageModule) },
  { path: 'mytripbookingdetail', loadChildren: () => import( './mytripbookingdetail/mytripbookingdetail.module').then( m => m.MytripBookingDetailPageModule) },
  { path: 'roomcancel', loadChildren: () => import( './roomcancel/roomcancel.module').then( m => m.RoomCancelPageModule) },
  { path: 'hotelnotes', loadChildren: () => import( './hotelnotes/hotelnotes.module').then( m => m.HotelNotesPageModule) },
  { path: 'hotelexpsnotes', loadChildren: () => import( './hotelexpsnotes/hotelexpsnotes.module').then( m => m.HotelExpsNotesPageModule) },
  { path: 'register', loadChildren: () => import( './register/register.module').then( m => m.RegisterPageModule) },
  { path: 'roomdetailreview', loadChildren: () => import( './roomdetailreview/roomdetailreview.module').then( m => m.RoomdetailreviewPageModule) },
  { path: 'roomadddetails', loadChildren: () => import( './roomadddetails/roomadddetails.module').then( m => m.RoomadddetailsPageModule) },
  { path: 'roomadddetails-ean', loadChildren: () => import( './roomadddetails-ean/roomadddetails-ean.module').then( m => m.RoomadddetailsEanPageModule) },
  { path: 'roompaymentselect', loadChildren: () => import( './roompaymentselect/roompaymentselect.module').then( m => m.RoompaymentselectPageModule) },
  { path: 'roompaymentselect-ean', loadChildren: () => import( './roompaymentselect-ean/roompaymentselect-ean.module').then( m => m.RoompaymentselectEanPageModule) },
  { path: 'roompaymentbank', loadChildren: () => import( './roompaymentbank/roompaymentbank.module').then( m => m.RoompaymentbankPageModule) },
  { path: 'roompaymentdone/:code/:stt', loadChildren: () => import( './roompaymentdone/roompaymentdone.module').then( m => m.RoompaymentdonePageModule) },
  { path: 'roompaymentlive/:stt', loadChildren: () => import( './roompaymentlive/roompaymentlive.module').then( m => m.RoompaymentlivePageModule) },
  { path: 'roomchoosebank/:stt', loadChildren: () => import( './roomchoosebank/roomchoosebank.module').then( m => m.RoomchoosebankPageModule) },
  { path: 'roompaymentdoneean/:code/:stt/:ischeck', loadChildren: () => import( './roompaymentdoneean/roompaymentdoneean.module').then( m => m.RoompaymentdoneeanPageModule) },
  { path: 'roompaymentbreakdown/:dur/:roomnumber', loadChildren: () => import( './roompaymentbreakdown/roompaymentbreakdown.module').then( m => m.RoompaymentbreakdownPageModule) },
  { path: 'flightcomboreviews', loadChildren: () => import( './flightcomboreviews/flightcomboreviews.module').then( m => m.FlightComboReviewsPageModule) },
  { path: 'flightdeparture', loadChildren: () => import( './flightdeparture/flightdeparture.module').then( m => m.FlightDeparturePageModule) },
  { path: 'flightcomboadddetails', loadChildren: () => import( './flightcomboadddetails/flightcomboadddetails.module').then( m => m.FlightComboAddDetailsPageModule) },
  { path: 'flightcombopaymentdone/:stt', loadChildren: () => import( './flightcombopaymentdone/flightcombopaymentdone.module').then( m => m.FlightComboPaymentDonePageModule) },
  { path: 'forgotpassword', loadChildren: () => import( './forgotpassword/forgotpassword.module').then( m => m.ForgotPasswordPageModule) },
  { path: 'blog/:id', loadChildren: () => import( './blog/blog.module').then( m => m.BlogPageModule) },
  { path: 'usertravelhobby',loadChildren: () => import( './usertravelhobby/usertravelhobby.module').then( m => m.UserTravelHobbyPageModule) },
  { path: 'bloglist', loadChildren: () => import( './bloglist/bloglist.module').then( m => m.BlogListPageModule) },
  { path: 'hotelreviewsimage', loadChildren: () => import( './hotelreviewsimage/hotelreviewsimage.module').then( m => m.HotelreviewsimagePageModule) },
  { path: 'topdeallist', loadChildren: () => import( './topdeallist/topdeallist.module').then( m => m.TopDealListPageModule) },
  { path: 'userfeedback', loadChildren: () => import( './userfeedback/userfeedback.module').then( m => m.UserFeedBackPageModule) },
  { path: 'confirmotp', loadChildren: () => import( './confirmotp/confirmotp.module').then( m => m.ConfirmotpPageModule) },
  { path: 'comboadddetails', loadChildren: () => import( './comboadddetails/comboadddetails.module').then( m => m.ComboadddetailsPageModule) },
  { path: 'combopayment', loadChildren: () => import( './combopayment/combopayment.module').then( m => m.CombopaymentPageModule) },
  { path: 'combodone/:code', loadChildren: () => import( './combodone/combodone.module').then( m => m.CombodonePageModule) },
  { path: 'carcombo', loadChildren: () => import( './carcombo/carcombo.module').then( m => m.CarComboPageModule) },
  { path: 'cardeparture', loadChildren: () => import( './cardeparture/cardeparture.module').then( m => m.CardeparturePageModule) },
  { path: 'combocarbank', loadChildren: () => import( './combocarbank/combocarbank.module').then( m => m.CombocarbankPageModule) },
  { path: 'combocarlive', loadChildren: () => import( './combocarlive/combocarlive.module').then( m => m.CombocarlivePageModule) },
  { path: 'loginsms', loadChildren: () => import( './loginsms/loginsms.module').then( m => m.LoginsmsPageModule) },
  { path: 'loginsmsverify', loadChildren: () => import( './loginsmsverify/loginsmsverify.module').then( m => m.LoginsmsverifyPageModule) },
  { path: 'searchblog', loadChildren: () => import( './searchblog/searchblog.module').then( m => m.SearchBlogPageModule) },
  { path: 'insurrancepopover', loadChildren: () => import( './insurrancepopover/insurrancepopover.module').then( m => m.InsurrancepopoverPageModule) },
  { path: 'insurrancehistorypopover', loadChildren: () => import( './insurrancehistorypopover/insurrancehistorypopover.module').then( m => m.InsurrancehistorypopoverPageModule) },
  { path: 'insurrancedetail', loadChildren: () => import( './insurrancedetail/insurrancedetail.module').then( m => m.InsurrancedetailPageModule) },
  { path: 'insurrancedone', loadChildren: () => import( './insurrancedone/insurrancedone.module').then( m => m.InsurrancedonePageModule) },
  { path: 'combochoosebank', loadChildren: () => import( './combochoosebank/combochoosebank.module').then( m => m.CombochoosebankPageModule) },
  { path: 'combodoneprepay/:code/:stt/:ischeck', loadChildren: () => import( './combodoneprepay/combodoneprepay.module').then( m => m.CombodoneprepayPageModule) },
  { path: 'forgotpass', loadChildren: () => import( './forgotpass/forgotpass.module').then( m => m.ForgotpassPageModule) },
  { path: 'forgotpassotp', loadChildren: () => import( './forgotpassotp/forgotpassotp.module').then( m => m.ForgotpassotpPageModule) },
  { path: 'forgotpasschange', loadChildren: () => import( './forgotpasschange/forgotpasschange.module').then( m => m.ForgotpasschangePageModule) },
  { path: 'combocarnew', loadChildren: () => import( './combocarnew/combocarnew.module').then( m => m.CombocarnewPageModule) },
  { path: 'combocarchangeplace', loadChildren: () => import( './combocarchangeplace/combocarchangeplace.module').then( m => m.CombocarchangeplacePageModule) },
  { path: 'insurrancenote', loadChildren: () => import( './insurrancenote/insurrancenote.module').then( m => m.InsurranceNotePageModule) },
  { path: 'registerverify', loadChildren: () => import( './registerverify/registerverify.module').then( m => m.RegisterverifyPageModule) },
  { path: 'popupinfobkg', loadChildren: () => import( './popupinfobkg/popupinfobkg.module').then( m => m.PopupinfobkgPageModule) },
  { path: 'adddiscount', loadChildren: () => import( './adddiscount/adddiscount.module').then( m => m.AdddiscountPageModule) },
  { path: 'combolist', loadChildren: () => import( './combolist/combolist.module').then( m => m.ComboListPageModule) },
  { path: 'flightcombopayment', loadChildren: () => import( './flightcombopayment/flightcombopayment.module').then( m => m.FlightcombopaymentPageModule) },
  { path: 'flightcombobank', loadChildren: () => import( './flightcombobank/flightcombobank.module').then( m => m.FlightcombobankPageModule) },
  { path: 'flightcombochosebank', loadChildren: () => import( './flightcombochosebank/flightcombochosebank.module').then( m => m.FlightcombochosebankPageModule) },
  { path: 'flightcombolive', loadChildren: () => import( './flightcombolive/flightcombolive.module').then( m => m.FlightcombolivePageModule) },
  { path: 'flightcombodoneprepay/:code/:stt/:ischeck', loadChildren: () => import( './flightcombodoneprepay/flightcombodoneprepay.module').then( m => m.FlightcombodoneprepayPageModule) },
  { path: 'rules', loadChildren: () => import( './rules/rules.module').then( m => m.RulesPageModule) },
  { path: 'cusimgreview/:stt', loadChildren: () => import( './cusimgreview/cusimgreview.module').then( m => m.CusimgreviewPageModule) },
  { path: 'combocarpaymentbreakdown', loadChildren: () => import( './combocarpaymentbreakdown/combocarpaymentbreakdown.module').then( m => m.CombocarpaymentbreakdownPageModule) },
  { path: 'flightcombopaymentbreakdown', loadChildren: () => import( './flightcombopaymentbreakdown/flightcombopaymentbreakdown.module').then( m => m.FlightcombopaymentbreakdownPageModule) },
  { path: 'installmentdetail', loadChildren: () => import( './installmentdetail/installmentdetail.module').then( m => m.InstallmentdetailPageModule) },
  { path: 'installmentpayment', loadChildren: () => import( './installmentpayment/installmentpayment.module').then( m => m.InstallmentpaymentPageModule) },

  { path: 'installmentpaymentdone', loadChildren: () => import( './installmentpaymentdone/installmentpaymentdone.module').then( m => m.InstallmentpaymentdonePageModule) },
 
  { path: 'userprofile', loadChildren: () => import( './userprofile/userprofile.module').then( m => m.UserProfilePageModule) },
  { path: 'userchangepassword', loadChildren: () => import( './userchangepassword/userchangepassword.module').then( m => m.UserChangePasswordPageModule) },
  { path: 'mytripaymentselect', loadChildren: () => import( './mytripaymentselect/mytripaymentselect.module').then( m => m.MytripaymentselectPageModule) },
  { path: 'mytripaymentchoosebank', loadChildren: () => import( './mytripaymentchoosebank/mytripaymentchoosebank.module').then( m => m.MytripaymentchoosebankPageModule) },


  { path: 'flightselectpax', loadChildren: () => import( './flightselectpax/flightselectpax.module').then( m => m.FlightselectpaxPageModule) },
  { path: 'flightsearchresult', loadChildren: () => import( './flightsearchresult/flightsearchresult.module').then( m => m.FlightsearchresultPageModule) },
  { path: 'flightsearchairport', loadChildren: () => import( './flightsearchairport/flightsearchairport.module').then( m => m.FlightsearchairportPageModule) },
  { path: 'flightsearcharea', loadChildren: () => import( './flightsearcharea/flightsearcharea.module').then( m => m.FlightSearchAreaPageModule) },
  { path: 'flightaddservice', loadChildren: () => import( './flightaddservice/flightaddservice.module').then( m => m.FlightaddservicePageModule) },
  { path: 'flightaddluggage', loadChildren: () => import( './flightaddluggage/flightaddluggage.module').then( m => m.FlightaddluggagePageModule) },
  { path: 'flightaddseat', loadChildren: () => import( './flightaddseat/flightaddseat.module').then( m => m.FlightaddseatPageModule) },
  { path: 'flightaddmeal', loadChildren: () => import( './flightaddmeal/flightaddmeal.module').then( m => m.FlightaddmealPageModule) },
  { path: 'flightadddetails', loadChildren: () => import( './flightadddetails/flightadddetails.module').then( m => m.FlightadddetailsPageModule) },
  { path: 'flightcondition', loadChildren: () => import( './flightcondition/flightcondition.module').then( m => m.FlightconditionPageModule) },
  { path: 'flightpaymentselect', loadChildren: () => import( './flightpaymentselect/flightpaymentselect.module').then( m => m.FlightPaymentSelectPageModule) },
  { path: 'flightpaymentbank', loadChildren: () => import( './flightpaymentbank/flightpaymentbank.module').then( m => m.FlightpaymentbankPageModule) },
  { path: 'flightpaymentchoosebank', loadChildren: () => import( './flightpaymentchoosebank/flightpaymentchoosebank.module').then( m => m.FlightpaymentchoosebankPageModule) },
  { path: 'flightpaymentdone/:code/:startdate/:enddate', loadChildren: () => import( './flightpaymentdone/flightpaymentdone.module').then( m => m.FlightpaymentdonePageModule) },
  { path: 'flightdetail', loadChildren: () => import( './flightdetail/flightdetail.module').then( m => m.FlightdetailPageModule) },
  { path: 'flightpaymentdonepayoo/:code/:startdate/:enddate', loadChildren: () => import( './flightpaymentdonepayoo/flightpaymentdonepayoo.module').then( m => m.FlightpaymentdonepayooPageModule) },
  { path: 'flightpaymentpayoo/:code/:stt', loadChildren: () => import( './flightpaymentpayoo/flightpaymentpayoo.module').then( m => m.FlightpaymentpayooPageModule) },
   { path: 'flightpaymentatoffice', loadChildren: () => import( './flightpaymentatoffice/flightpaymentatoffice.module').then( m => m.FlightpaymentatofficePageModule) },
  { path: 'flightpaymenterror', loadChildren: () => import( './flightpaymenterror/flightpaymenterror.module').then( m => m.FlightpaymenterrorPageModule) },
  { path: 'flightpaymentwarning', loadChildren: () => import( './flightpaymentwarning/flightpaymentwarning.module').then( m => m.FlightpaymentwarningPageModule) },
  { path: 'flightcombowarning', loadChildren: () => import( './flightcombowarning/flightcombowarning.module').then( m => m.FlightcombowarningPageModule) },
  { path: 'roompaymentbanknew', loadChildren: () => import( './roompaymentbanknew/roompaymentbanknew.module').then( m => m.RoompaymentbanknewPageModule) },
  { path: 'roompaymentdonenew/:code/:stt', loadChildren: () => import( './roompaymentdonenew/roompaymentdonenew.module').then( m => m.RoompaymentdonenewPageModule) },
  { path: 'flightpaymentdonebank/:code/:startdate/:enddate', loadChildren: () => import( './flightpaymentdonebank/flightpaymentdonebank.module').then( m => m.FlightpaymentdonebankPageModule) },
  { path: 'combodonebank/:code', loadChildren: () => import( './combodonebank/combodonebank.module').then( m => m.CombodonebankPageModule) },
  { path: 'flightcombopaymentdonebank/:stt', loadChildren: () => import( './flightcombopaymentdonebank/flightcombopaymentdonebank.module').then( m => m.FlightcombopaymentdonebankPageModule) },
  { path: 'flightcombobookingdetail', loadChildren: () => import( './flightcombobookingdetail/flightcombobookingdetail.module').then( m => m.FlightcombobookingdetailPageModule) },

  //{ path: 'flightcombobookingdetail', loadChildren: () => import( './flightcombobookingdetail/flightcombobookingdetail.module#FlightcombobookingdetailPageModule' },
  { path: 'flighttopdealdetail', loadChildren: () => import( './flighttopdealdetail/flighttopdealdetail.module').then( m => m.FlighttopdealdetailPageModule) },
  { path: 'flightusefuldetail', loadChildren: () => import( './flightusefuldetail/flightusefuldetail.module').then( m => m.FlightUsefulDetailPageModule) },

  { path: 'flightcomboaddluggage', loadChildren: () => import( './flightcomboaddluggage/flightcomboaddluggage.module').then( m => m.FlightcomboaddluggagePageModule) },
  { path: 'flightcomboinfoluggage', loadChildren: () => import( './flightcomboinfoluggage/flightcomboinfoluggage.module').then( m => m.FlightcomboinfoluggagePageModule) },
  { path: 'roompaymentpayoo/:code/:stt', loadChildren: () => import( './roompaymentpayoo/roompaymentpayoo.module').then( m => m.RoompaymentpayooPageModule) },
  //{ path: 'combocarpaymentpayoo/:code/:stt', loadChildren: () => import( './combocarpaymentpayoo/combocarpaymentpayoo.module#CombocarpaymentpayooPageModule' },
  //{ path: 'flightcombopaymentnew', loadChildren: () => import( './flightcombopaymentnew/flightcombopaymentnew.module#FlightcombopaymentnewPageModule' },
  //{ path: 'flightcombopaymentpayoo/:code/:stt', loadChildren: () => import( './flightcombopaymentpayoo/flightcombopaymentpayoo.module#FlightcombopaymentpayooPageModule' },   
  { path: 'flightcombopaymentpayoonew/:code/:stt', loadChildren: () => import( './flightcombopaymentpayoonew/flightcombopaymentpayoonew.module').then( m => m.FlightcombopaymentpayoonewPageModule) },
  { path: 'combocarpaymentpayoonew/:code/:stt', loadChildren: () => import( './combocarpaymentpayoonew/combocarpaymentpayoonew.module').then( m => m.CombocarpaymentpayoonewPageModule) },
  { path: 'flightpaymenttimeout/:stt', loadChildren: () => import( './flightpaymenttimeout/flightpaymenttimeout.module').then( m => m.FlightpaymenttimeoutPageModule) },
  //thêm mới thanh toán lại từ mytrip
  { path: 'mytripaymentselect/:stt', loadChildren: () => import( './mytripaymentselect/mytripaymentselect.module').then( m => m.MytripaymentselectPageModule) },
  { path: 'mytripaymentflightselect/:stt', loadChildren: () => import( './mytripaymentflightselect/mytripaymentflightselect.module').then( m => m.MytripaymentflightselectPageModule) },
  { path: 'mytripaymentflightcombo/:stt', loadChildren: () => import( './mytripaymentflightcombo/mytripaymentflightcombo.module').then( m => m.MytripaymentflightcomboPageModule) },
  { path: 'mytripaymentcarcombo/:stt', loadChildren: () => import( './mytripaymentcarcombo/mytripaymentcarcombo.module').then( m => m.MytripaymentcarcomboPageModule) },
  { path: 'mytripaymentflightbank', loadChildren: () => import( './mytripaymentflightbank/mytripaymentflightbank.module').then( m => m.MytripaymentflightbankPageModule) },
  { path: 'mytripaymentflighdone', loadChildren: () => import( './mytripaymentflighdone/mytripaymentflighdone.module').then( m => m.MytripaymentflighdonePageModule) },
  { path: 'mytripaymentflightpayoo/:code/:stt', loadChildren: () => import( './mytripaymentflightpayoo/mytripaymentflightpayoo.module').then( m => m.MytripaymentflightpayooPageModule) },
  { path: 'selectdaterange', loadChildren: () => import( './selectdaterange/selectdaterange.module').then( m => m.SelectDateRangePageModule) },
  { path: 'hotellistmoodfilter', loadChildren: () => import( './hotellistmoodfilter/hotellistmoodfilter.module').then( m => m.HotellistmoodfilterPageModule) },
  { path: 'flightcardbamboo', loadChildren: () => import( './flightcardbamboo/flightcardbamboo.module').then( m => m.FlightcardbambooPageModule) },
  { path: 'mytriphistory', loadChildren: () => import( './mytriphistory/mytriphistory.module').then( m => m.MytripHistoryPageModule) },
  { path: 'mytripdetail', loadChildren: () => import( './mytripdetail/mytripdetail.module').then( m => m.MytripdetailPageModule) },

  //add hotel city
  { path: 'hotelcityitemdetail', loadChildren: () => import( './hotelcityitemdetail/hotelcityitemdetail.module').then( m => m.HotelCityItemDetailPageModule) },
  { path: 'hotelcityroomupgrade', loadChildren: () => import( './hotelcityroomupgrade/hotelcityroomupgrade.module').then( m => m.HotelCityRoomUpgradePageModule) },
  
  // { path: 'flightdcpickaddress', loadChildren: () => import( './flightdcpickaddress/flightdcpickaddress.module#FlightdcpickaddressPageModule' },
  // { path: 'flightdcpickaddressinput', loadChildren: () => import( './flightdcpickaddressinput/flightdcpickaddressinput.module#FlightdcpickaddressinputPageModule' },
  // { path: 'flightdcdetail/:isDepart/:isReturn', loadChildren: () => import( './flightdcdetail/flightdcdetail.module#FlightdcdetailPageModule' },
  { path: 'flightdcpickaddress', loadChildren: () => import( './flightdcpickaddress/flightdcpickaddress.module').then( m => m.FlightdcpickaddressPageModule) },
  { path: 'flightdcpickaddressinput', loadChildren: () => import( './flightdcpickaddressinput/flightdcpickaddressinput.module').then( m => m.FlightdcpickaddressinputPageModule) },
  { path: 'flightdcdetail/:isDepart/:isReturn', loadChildren: () => import( './flightdcdetail/flightdcdetail.module').then( m => m.FlightdcdetailPageModule) },
  { path: 'mytrippaymentbank', loadChildren: () => import( './mytrippaymentbank/mytrippaymentbank.module').then( m => m.MytrippaymentbankPageModule) },
  { path: 'ordersupport/:stt', loadChildren: () => import( './ordersupport/ordersupport.module').then( m => m.OrdersupportPageModule) },
  { path: 'ordersupportdone', loadChildren: () => import( './ordersupportdone/ordersupportdone.module').then( m => m.OrdersupportdonePageModule) },
  { path: 'mytripcathay/:bookingid', loadChildren: () => import( './mytripcathay/mytripcathay.module').then( m => m.MytripcathayPageModule) },
  
  { path: 'companyinfo', loadChildren: () => import( './bizTravel/companyinfo/companyinfo.module').then( m => m.CompanyinfoPageModule) },
  { path: 'bookingdetail', loadChildren: () => import( './bizTravel/bookingdetail/bookingdetail.module').then( m => m.BookingDetailPageModule) },
  { path: 'bookinghoteldetail', loadChildren: () => import( './bizTravel/bookinghoteldetail/bookinghoteldetail.module').then( m => m.BookingHotelDetailPageModule) },
  { path: 'confirmpayment', loadChildren: () => import( './bizTravel/confirmpayment/confirmpayment.module').then( m => m.ConfirmPaymentPageModule) },
  { path: 'confirmpaymentdone', loadChildren: () => import( './bizTravel/confirmpaymentdone/confirmpaymentdone.module').then( m => m.ConfirmPaymentDonePageModule) },
  { path: 'topup', loadChildren: () => import( './bizTravel/topup/topup.module').then( m => m.TopupPageModule) },
  { path: 'paymentdetail', loadChildren: () => import( './bizTravel/paymentdetail/paymentdetail.module').then( m => m.PaymentDetailPageModule) },

  { path: 'userlinkprofile', loadChildren: () => import( './userlinkprofile/userlinkprofile.module').then( m => m.UserLinkProfilePageModule), },
  { path: 'userprivacypolicy', loadChildren: () => import( './userprivacypolicy/userprivacypolicy.module').then( m => m.UserPrivacyPolicyPageModule), },
  { path: 'usercondition', loadChildren: () => import( './usercondition/usercondition.module').then( m => m.UserConditionPageModule), },
  { path: 'userzalo', loadChildren: () => import( './userzalo/userzalo.module').then( m => m.UserZaloPageModule), },

  { path: 'hotelupgraderoom',  loadChildren: () => import( './hotelupgraderoom/hotelupgraderoom.module').then( m => m.HotelupgraderoomPageModule), },
  {
    path: 'roomimagedetail',
    loadChildren: () => import('./roomimagedetail/roomimagedetail.module').then( m => m.RoomimagedetailPageModule)
  },

  { path: 'orderrequestsupport',  loadChildren: () => import('./orderrequestsupport/orderrequestsupport/orderrequestsupport.module').then( m => m.OrderRequestSupportPageModule) },
  { path: 'orderrequestaddluggage',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggage/orderrequestaddluggage.module').then( m => m.OrderRequestAddluggagePageModule) },
  { path: 'orderrequestaddluggagepaymentselect',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentselect/orderrequestaddluggagepaymentselect.module').then( m => m.OrderRequestAddluggagePaymentSelectPageModule) },
  { path: 'orderrequestaddluggagepaymentdone',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentdone/orderrequestaddluggagepaymentdone.module').then( m => m.OrderRequestAddluggagePaymentDonePageModule) },

  { path: 'orderrequestaddluggagepaymentatoffice',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentatoffice/orderrequestaddluggagepaymentatoffice.module').then( m => m.OrderRequestAddluggagePaymentAtOfficePageModule) },
  { path: 'orderrequestaddluggagepaymentbank',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentbank/orderrequestaddluggagepaymentbank.module').then( m => m.OrderRequestAddluggagePaymentBankPageModule) },
  { path: 'orderrequestaddluggagepaymentchoosebank',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentchoosebank/orderrequestaddluggagepaymentchoosebank.module').then( m => m.OrderRequestAddluggagePaymentChooseBankPageModule) },
  { path: 'orderrequestaddluggagepaymentpayoo/:code/:stt',  loadChildren: () => import( './orderrequestsupport/orderrequestaddluggagepaymentpayoo/orderrequestaddluggagepaymentpayoo.module').then( m => m.OrderRequestAddluggagePaymentPayooPageModule) },
  
  { path: 'orderrequestchangeflight',  loadChildren: () => import( './orderrequestsupport/orderrequestchangeflight/orderrequestchangeflight.module').then( m => m.OrderRequestChangeFlightPageModule) },
  { path: 'orderrequestsearchflight',  loadChildren: () => import( './orderrequestsupport/orderrequestsearchflight/orderrequestsearchflight.module').then( m => m.OrderRequestSearchFlightPageModule) },
  { path: 'orderrequestchangeflightpaymentselect',  loadChildren: () => import( './orderrequestsupport/orderrequestchangeflightpaymentselect/orderrequestchangeflightpaymentselect.module').then( m => m.OrderRequestChangeFlightPaymentSelectPageModule) },

  {
    path: 'shuttlebusnote',
    loadChildren: () => import('./shuttlebusnote/shuttlebusnote.module').then( m => m.ShuttlebusnotePageModule)
  },

  { path: 'myvoucher', loadChildren: () => import('./voucher/myvoucher/myvoucher.module').then( m => m.MyVoucherPageModule) },

  //tour
  { path: 'hometour', loadChildren: () => import('./tour/hometour/hometour.module').then( m => m.HomeTourPageModule) },
  { path: 'tourdetail', loadChildren: () => import('./tour/tourdetail/tourdetail.module').then( m => m.TourDetailPageModule) },
  { path: 'searchregion', loadChildren: () => import('./tour/hometour/hometourcomponent/searchregion/searchregion.module').then( m => m.SearchRegionPageModule) },
  { path: 'searchdeparture', loadChildren: () => import('./tour/hometour/hometourcomponent/searchdeparture/searchdeparture.module').then( m => m.SearchDeparturePageModule) },
  { path: 'tourlist', loadChildren: () => import('./tour/tourlist/tourlist.module').then( m => m.TourListPageModule) },
  { path: 'tourdeparturecalendar', loadChildren: () => import('./tour/tourdeparturecalendar/tourdeparturecalendar.module').then( m => m.TourDepartureCalendarPageModule) },
  { path: 'touradddetails', loadChildren: () => import('./tour/touradddetails/touradddetails.module').then( m => m.TourAddDetailsPageModule) },
  { path: 'tourpaymentselect', loadChildren: () => import('./tour/tourpaymentselect/tourpaymentselect.module').then( m => m.TourPaymentSelectPageModule) },
  { path: 'tourpaymentatm', loadChildren: () => import('./tour/tourpaymentatm/tourpaymentatm.module').then( m => m.TourPaymentAtmPageModule) },
  { path: 'tourpaymentbank', loadChildren: () => import('./tour/tourpaymentbank/tourpaymentbank.module').then( m => m.TourPaymentBankPageModule) },
  { path: 'tourpaymentatoffice', loadChildren: () => import('./tour/tourpaymentatoffice/tourpaymentatoffice.module').then( m => m.TourPaymentAtOfficePageModule) },
  { path: 'tourpaymentpayoo/:code/:stt', loadChildren: () => import('./tour/tourpaymentpayoo/tourpaymentpayoo.module').then( m => m.TourPaymentPayooPageModule) },
  { path: 'tourpaymentdone', loadChildren: () => import('./tour/tourpaymentdone/tourpaymentdone.module').then( m => m.TourPaymentDonePageModule) },
  { path: 'tourrequestdone', loadChildren: () => import('./tour/tourrequestdone/tourrequestdone.module').then( m => m.TourRequestDonePageModule) },
  { path: 'mytriptourinfo', loadChildren: () => import('./tour/mytriptourinfo/mytriptourinfo.module').then( m => m.MyTripTourInfoPageModule) },
  //VMBQT
  { path: 'flightsearchresultinternational', loadChildren: () => import('./flightinternational/flightsearchresultinternational/flightsearchresultinternational.module').then( m => m.FlightSearchResultInternationalPageModule) },
  { path: 'flightadddetailsinternational', loadChildren: () => import('./flightinternational/flightadddetailsinternational/flightadddetailsinternational.module').then( m => m.FlightAdddetailsInternationalPageModule) },
  { path: 'flightinternationalpaymentselect', loadChildren: () => import('./flightinternational/flightinternationalpaymentselect/flightinternationalpaymentselect.module').then( m => m.FlightInternationalPaymentSelectPageModule) },
  { path: 'flightinternationalpaymentatoffice', loadChildren: () => import('./flightinternational/flightinternationalpaymentatoffice/flightinternationalpaymentatoffice.module').then( m => m.FlightInternationalPaymentatOfficePageModule) },
  { path: 'flightinternationalpaymentbank', loadChildren: () => import('./flightinternational/flightinternationalpaymentbank/flightinternationalpaymentbank.module').then( m => m.FlightInternationalPaymentBankPageModule) },
  { path: 'flightinternationalpaymentchoosebank', loadChildren: () => import('./flightinternational/flightinternationalpaymentchoosebank/flightinternationalpaymentchoosebank.module').then( m => m.FlightInternationalPaymentChooseBankPageModule) },
  { path: 'flightinternationalpaymentdone/:code/:startdate/:enddate', loadChildren: () => import('./flightinternational/flightinternationalpaymentdone/flightinternationalpaymentdone.module').then( m => m.FlightInternationalPaymentDoneModule) },
  { path: 'flightinternationalpaymentdonebank/:code/:startdate/:enddate', loadChildren: () => import('./flightinternational/flightinternationalpaymentdonebank/flightinternationalpaymentdonebank.module').then( m => m.FlightInternationalPaymentDoneBankPageModule) },
  { path: 'flightinternationalpaymentdonepayoo/:code/:startdate/:enddate', loadChildren: () => import('./flightinternational/flightinternationalpaymentdonepayoo/flightinternationalpaymentdonepayoo.module').then( m => m.FlightInternationalPaymentDonePayooPageModule) },
  { path: 'flightinternationalpaymenterror', loadChildren: () => import('./flightinternational/flightinternationalpaymenterror/flightinternationalpaymenterror.module').then( m => m.FlightInternationalPaymentErrorPageModule) },
  { path: 'flightinternationalpaymentpayoo/:code/:stt', loadChildren: () => import('./flightinternational/flightinternationalpaymentpayoo/flightinternationalpaymentpayoo.module').then( m => m.FlightInternationalPaymentPayooPageModule) },
  { path: 'flightinternationalpaymenttimeout/:stt', loadChildren: () => import('./flightinternational/flightinternationalpaymenttimeout/flightinternationalpaymenttimeout.module').then( m => m.FlightInternationalPaymentTimeoutPageModule) },
  { path: 'flightinternationalpaymentwarning', loadChildren: () => import('./flightinternational/flightinternationalpaymentwarning/flightinternationalpaymentwarning.module').then( m => m.FlightInternationalPaymentwarningPageModule) },

  { path: 'flighttopplan', loadChildren: () => import('./flighttopplan/flighttopplan.module').then( m => m.FlighttopplanPageModule) },
  { path: 'flighttopreview',loadChildren: () => import('./flighttopreview/flighttopreview.module' ).then( m => m.FlightTopReviewPageModule) },
  { path: 'flighttopreviewlist', loadChildren: () => import('./flighttopreviewlist/flighttopreviewlist.module' ).then( m => m.FlightTopReviewListPageModule) },


  { path: 'paymentqrcode',loadChildren: () => import('./paymentqrcode/paymentqrcode.module').then(m => m.PaymentqrcodePageModule) },
  // Ticket  
  { path: 'ticketsearch',loadChildren: () => import('./ticket/ticketsearch/ticketsearch.module').then(m => m.TicketSearchPageModule) },
  { path: 'ticketlist/:stt',loadChildren: () => import('./ticket/ticketlist/ticketlist.module').then(m => m.TicketListPageModule) },
  { path: 'ticketdetail',loadChildren: () => import('./ticket/ticketdetail/ticketdetail.module').then(m => m.TicketDetailPageModule) },
  { path: 'ticketservice',loadChildren: () => import('./ticket/ticketservice/ticketservice.module').then(m => m.TicketServicePageModule) },
  { path: 'ticketservicedetail',loadChildren: () => import('./ticket/ticketservicedetail/ticketservicedetail.module').then(m => m.TicketServiceDetailPageModule) },
  { path: 'ticketadddetails',loadChildren: () => import('./ticket/ticketadddetails/ticketadddetails.module').then(m => m.TicketAdddetailsPageModule) },
  { path: 'ticketpricedetail',loadChildren: () => import('./ticket/ticketpricedetail/ticketpricedetail.module').then(m => m.TicketPriceDetailPageModule) },
  { path: 'ticketpaymentselect',loadChildren: () => import('./ticket/ticketpaymentselect/ticketpaymentselect.module').then(m => m.TicketPaymentSelectPageModule) },
  { path: 'ticketpaymentatm/:stt',loadChildren: () => import('./ticket/ticketpaymentatm/ticketpaymentatm.module').then(m => m.TicketPaymentAtmPageModule) },
  
  { path: 'ticketpaymentpayoo/:code/:stt',loadChildren: () => import('./ticket/ticketpaymentpayoo/ticketpaymentpayoo.module').then(m => m.TicketPaymentPayooPageModule) },
  { path: 'ticketpaymentdone/:stt',loadChildren: () => import('./ticket/ticketpaymentdone/ticketpaymentdone.module').then(m => m.TicketPaymentDonePageModule) },
  { path: 'ticketinfo/:code',loadChildren: () => import('./ticket/ticketinfo/ticketinfo.module').then(m => m.TicketinfoPageModule) },
  { path: 'ticketpaymentfail',loadChildren: () => import('./ticket/ticketpaymentfail/ticketpaymentfail.module').then(m => m.TicketpaymentfailPageModule) },
  { path: 'ticketpaymentatoffice',loadChildren: () => import('./ticket/ticketpaymentatoffice/ticketpaymentatoffice.module').then(m => m.TicketPaymentAtOfficePageModule) },
  { path: 'ticketpaymentbank',loadChildren: () => import('./ticket/ticketpaymentbank/ticketpaymentbank.module').then(m => m.TicketpaymentbankPageModule) },
  { path: 'ticketfilter', loadChildren: () => import( './ticket/ticketfilter/ticketfilter.module').then(m => m.TicketfilterPageModule) },
  { path: 'ticketfilterlist', loadChildren: () => import( './ticket/ticketfilterlist/ticketfilterlist.module').then(m => m.TicketfilterlistPageModule) },

  { path: 'accountdeletiondone', loadChildren: () => import('./accountdeletiondone/accountdeletiondone.module').then( m => m.AccountDeletionDonePageModule) },
  { path: 'accountdeletion', loadChildren: () => import('./accountdeletion/accountdeletion.module').then( m => m.AccountDeletionPageModule) }
 
  
];
@NgModule({
  imports:
    [
      RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
    ],
  exports:
    [
      RouterModule
    ]
})
export class AppRoutingModule { }
